DROP DATABASE IF EXISTS RECIPIENTS;

CREATE DATABASE RECIPIENTS;

USE RECIPIENTS;

CREATE TABLE Recipients (
	AwardID INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Year INT NOT NULL,
    City VARCHAR(50) NOT NULL,
    Category VARCHAR(50) NOT NULL
);

INSERT INTO Recipients (AwardID, Name, Year, City, Category)
VALUES
(1, 'Smith; James', 1987, 'Toronto', 'Science and Medicine'),
(2, 'Brown; Mary', 1987, 'Ottawa', 'Arts and Culture'),
(3, 'Williams; John', 1987, 'Hamilton', 'Public Service'),
(4, 'Johnson; Patricia', 1988, 'Toronto', 'Business and Economy'),
(5, 'Jones; Robert', 1988, 'Ottawa', 'Education'),
(6, 'Miller; Jennifer', 1988, 'Hamilton', 'Volunteerism'),
(7, 'Davis; Michael', 1989, 'Toronto', 'Science and Medicine'),
(8, 'Garcia; Linda', 1989, 'Ottawa', 'Arts and Culture'),
(9, 'Rodriguez; William', 1989, 'Hamilton', 'Public Service'),
(10, 'Wilson; Elizabeth', 1990, 'Toronto', 'Business and Economy'),
(11, 'Martinez; David', 1990, 'Ottawa', 'Education'),
(12, 'Anderson; Barbara', 1990, 'Hamilton', 'Volunteerism'),
(13, 'Taylor; Richard', 1991, 'Toronto', 'Science and Medicine'),
(14, 'Thomas; Susan', 1991, 'Ottawa', 'Arts and Culture'),
(15, 'Hernandez; Joseph', 1991, 'Hamilton', 'Public Service'),
(16, 'Moore; Jessica', 1992, 'Toronto', 'Business and Economy'),
(17, 'Martin; Thomas', 1992, 'Ottawa', 'Education'),
(18, 'Jackson; Sarah', 1992, 'Hamilton', 'Volunteerism'),
(19, 'Thompson; Charles', 1993, 'Toronto', 'Science and Medicine'),
(20, 'White; Karen', 1993, 'Ottawa', 'Arts and Culture'),
(21, 'Lopez; Christopher', 1993, 'Hamilton', 'Public Service'),
(22, 'Lee; Nancy', 1994, 'Toronto', 'Business and Economy'),
(23, 'Gonzalez; Daniel', 1994, 'Ottawa', 'Education'),
(24, 'Harris; Margaret', 1994, 'Hamilton', 'Volunteerism'),
(25, 'Clark; Matthew', 1995, 'Toronto', 'Science and Medicine'),
(26, 'Lewis; Lisa', 1995, 'Ottawa', 'Arts and Culture'),
(27, 'Robinson; Anthony', 1995, 'Hamilton', 'Public Service'),
(28, 'Walker; Betty', 1996, 'Toronto', 'Business and Economy'),
(29, 'Perez; Mark', 1996, 'Ottawa', 'Education'),
(30, 'Hall; Helen', 1996, 'Hamilton', 'Volunteerism'),
(31, 'Young; Donald', 1997, 'Toronto', 'Science and Medicine'),
(32, 'Allen; Sandra', 1997, 'Ottawa', 'Arts and Culture'),
(33, 'Sanchez; Steven', 1997, 'Hamilton', 'Public Service'),
(34, 'Wright; Donna', 1998, 'Toronto', 'Business and Economy'),
(35, 'Smith; George', 1998, 'Ottawa', 'Education'),
(36, 'Brown; Mary', 1998, 'Hamilton', 'Volunteerism'),
(37, 'Williams; John', 1999, 'Toronto', 'Science and Medicine'),
(38, 'Johnson; Patricia', 1999, 'Ottawa', 'Arts and Culture'),
(39, 'Jones; Robert', 1999, 'Hamilton', 'Public Service'),
(40, 'Miller; Jennifer', 2000, 'Toronto', 'Business and Economy'),
(41, 'Davis; Michael', 2000, 'Ottawa', 'Education'),
(42, 'Garcia; Linda', 2000, 'Hamilton', 'Volunteerism'),
(43, 'Rodriguez; William', 2001, 'Toronto', 'Science and Medicine'),
(44, 'Wilson; Elizabeth', 2001, 'Ottawa', 'Arts and Culture'),
(45, 'Martinez; David', 2001, 'Hamilton', 'Public Service'),
(46, 'Anderson; Barbara', 2002, 'Toronto', 'Business and Economy'),
(47, 'Taylor; Richard', 2002, 'Ottawa', 'Education'),
(48, 'Thomas; Susan', 2002, 'Hamilton', 'Volunteerism'),
(49, 'Hernandez; Joseph', 2003, 'Toronto', 'Science and Medicine'),
(50, 'Moore; Jessica', 2003, 'Ottawa', 'Arts and Culture'),
(51, 'Martin; Thomas', 2003, 'Hamilton', 'Public Service'),
(52, 'Jackson; Sarah', 2004, 'Toronto', 'Business and Economy'),
(53, 'Thompson; Charles', 2004, 'Ottawa', 'Education'),
(54, 'White; Karen', 2004, 'Hamilton', 'Volunteerism'),
(55, 'Lopez; Christopher', 2005, 'Toronto', 'Science and Medicine'),
(56, 'Lee; Nancy', 2005, 'Ottawa', 'Arts and Culture'),
(57, 'Gonzalez; Daniel', 2005, 'Hamilton', 'Public Service'),
(58, 'Harris; Margaret', 2006, 'Toronto', 'Business and Economy'),
(59, 'Clark; Matthew', 2006, 'Ottawa', 'Education'),
(60, 'Lewis; Lisa', 2006, 'Hamilton', 'Volunteerism'),
(61, 'Robinson; Anthony', 2007, 'Toronto', 'Science and Medicine'),
(62, 'Walker; Betty', 2007, 'Ottawa', 'Arts and Culture'),
(63, 'Perez; Mark', 2007, 'Hamilton', 'Public Service'),
(64, 'Hall; Helen', 2008, 'Toronto', 'Business and Economy'),
(65, 'Young; Donald', 2008, 'Ottawa', 'Education'),
(66, 'Allen; Sandra', 2008, 'Hamilton', 'Volunteerism'),
(67, 'Sanchez; Steven', 2009, 'Toronto', 'Science and Medicine'),
(68, 'Wright; Donna', 2009, 'Ottawa', 'Arts and Culture'),
(69, 'Smith; George', 2009, 'Hamilton', 'Public Service'),
(70, 'Brown; Mary', 2010, 'Toronto', 'Business and Economy'),
(71, 'Williams; John', 2010, 'Ottawa', 'Education'),
(72, 'Johnson; Patricia', 2010, 'Hamilton', 'Volunteerism'),
(73, 'Jones; Robert', 2011, 'Toronto', 'Science and Medicine'),
(74, 'Miller; Jennifer', 2011, 'Ottawa', 'Arts and Culture'),
(75, 'Davis; Michael', 2011, 'Hamilton', 'Public Service'),
(76, 'Garcia; Linda', 2012, 'Toronto', 'Business and Economy'),
(77, 'Rodriguez; William', 2012, 'Ottawa', 'Education'),
(78, 'Wilson; Elizabeth', 2012, 'Hamilton', 'Volunteerism'),
(79, 'Martinez; David', 2013, 'Toronto', 'Science and Medicine'),
(80, 'Anderson; Barbara', 2013, 'Ottawa', 'Arts and Culture'),
(81, 'Taylor; Richard', 2013, 'Hamilton', 'Public Service'),
(82, 'Thomas; Susan', 2014, 'Toronto', 'Business and Economy'),
(83, 'Hernandez; Joseph', 2014, 'Ottawa', 'Education'),
(84, 'Moore; Jessica', 2014, 'Hamilton', 'Volunteerism'),
(85, 'Martin; Thomas', 2015, 'Toronto', 'Science and Medicine'),
(86, 'Jackson; Sarah', 2015, 'Ottawa', 'Arts and Culture'),
(87, 'Thompson; Charles', 2015, 'Hamilton', 'Public Service'),
(88, 'White; Karen', 2016, 'Toronto', 'Business and Economy'),
(89, 'Lopez; Christopher', 2016, 'Ottawa', 'Education'),
(90, 'Lee; Nancy', 2016, 'Hamilton', 'Volunteerism'),
(91, 'Gonzalez; Daniel', 2017, 'Toronto', 'Science and Medicine'),
(92, 'Harris; Margaret', 2017, 'Ottawa', 'Arts and Culture'),
(93, 'Clark; Matthew', 2017, 'Hamilton', 'Public Service'),
(94, 'Lewis; Lisa', 2018, 'Toronto', 'Business and Economy'),
(95, 'Robinson; Anthony', 2018, 'Ottawa', 'Education'),
(96, 'Walker; Betty', 2018, 'Hamilton', 'Volunteerism'),
(97, 'Perez; Mark', 2019, 'Toronto', 'Science and Medicine'),
(98, 'Hall; Helen', 2019, 'Ottawa', 'Arts and Culture'),
(99, 'Young; Donald', 2019, 'Hamilton', 'Public Service'),
(100, 'Allen; Sandra', 2020, 'Toronto', 'Business and Economy'),
(101, 'Sanchez; Steven', 2020, 'Ottawa', 'Education'),
(102, 'Wright; Donna', 2020, 'Hamilton', 'Volunteerism');